### ISSUE TITLE
LimeSurvey.get_label returning wrong values

### ISSUE THREAD

**Issue by olineumann** [N2-Survey/SurveyFramework#49] opened 2021-11-16 10:42 UTC
## Description

It seems like the `LimeSurvey.get_labels` method returns wrong or misleading values for array type questions (and maybe also others). 

## Reproduce

I debugged the LimeSurveyGetResponses tests to replace the label parsing in get_response with the get_label method of the LimeSurvey class. There I recognized the following when comparing the labels:
```
> question
'B6'
> response
name B6_SQ001 B6_SQ002 B6_SQ003
id                             
2          A1       A1       A2
3          A1       A1       A1
4          A1       A1       A3
...
> self.get_label(question)
'Would it be possible for you to extend your current contract/stipend for the following reasons?'
> question_group.label
name
B6_SQ001             More time needed to complete PhD project
B6_SQ002                                       Parental leave
B6_SQ003    Wrap-up phase after completion of the PhD project
Name: label, dtype: object
>question_group.choices
name
B6_SQ001    {'A1': 'Yes', 'A2': 'No', 'A3': 'I don't know'...
B6_SQ002    {'A1': 'Yes', 'A2': 'No', 'A3': 'I don't know'...
B6_SQ003    {'A1': 'Yes', 'A2': 'No', 'A3': 'I don't know'...
Name: choices, dtype: object
```

## Expection

I would expect to get the labels for B6_SQ001, ..., B6_SQ003 when performing `survey.get_labels(..)`. Otherwise, I would rename the `label` attribute of `survey.get_question(..)` because it is misleading (see above). I would prefer to add a method named survey.get_question_name that returns the name of the question like currently for array type questions and the actual labels otherwise. Also, we could return a dict with `{'name': ..., 'B6_SQ001': ..., ..., 'B6_SQ003': ...}` for questions like array and multiple-choice.

## Additional context

Code of current main branch [ed6ec73](https://github.com/N2-Survey/SurveyFramework/tree/ed6ec73f00ff9381bf41d2f2b54cd2194ed77898). Python version 3.9.7.

**Comment by rguliev** [comment] 2021-11-16 15:30
I wouldn't call it a bug. This is intended behavior. The problem is that we have a label for an individual (sub)question/column and for the whole question group (see `servey.questions.question_label`).
So, it is not easy to decide what is the label. The current logic is that we return a column label if for a specific column, and a question label for a question group.

Maybe, we need to separate getting "question_label" and "labels" into different methods. Or, for example, return a tuple with both.

**Comment by rguliev** [comment] 2021-11-25 08:53
Closing this issue, since the output is as intended. I think we create a separate issue when we get more specific requirements.

**Closed by rguliev** 2021-11-25 08:53 UTC
